### ISSUE TITLE
파일 업로드 후 뒤로가기를 한 다음, 다시 파일을 올리려고 할 경우, 안됨.

### ISSUE THREAD

**Issue by minhoryang** [juice-ryang/online-judge#10]

**Comment by juice500ml** [comment]
?? 제꺼에서는 잘됩니당 혹시 .txt나 .py 말고 다른걸 업로드하려고 하신건 아닌지요?

**Comment by minhoryang** [comment]
흠!!! 다시해볼게요!!!!!

**Comment by minhoryang** [comment]
file-input-new class가 새로고침 후에는 지워지지 않네요.

**Comment by minhoryang** [comment]
document.onready로 해결하려고했는데 안되더라구요?!
refresh라는 기능이 있어서 그걸 써봤습니다;;

**Comment by minhoryang** [comment]
아마 제가 생각하는 시나리오는.
1. 파일을 선택한다.
2. 전송을 누른다
3. 뒤로가기를 누른다
4. 이때 사실 파일이 이미 선택되어있다.
5. 그런데 bootstrap-fileinput의 ui가 이를 알아채지 못했고
6. 여기서 새 파일을 선택하면
7. 새 파일이 등록되면서 ui가 바뀌어야하는데,
8. 사실 file form에는 이미 파일이 등록되어있어서
9. bootstrap-fileinput에게 이벤트가 등록이벤트가 전달이 안되는것 같음.
10. 그래서 refresh를 하게함.
