### ISSUE TITLE
채점 프로그램이 돌기 시작!

### ISSUE THREAD

**Issue by minhoryang** [juice-ryang/online-judge#11]
[동영상보기](http://r.reluv.me/fOnj)

**Comment by minhoryang** [comment]
실서버에도 적용이 되었음!
접속해서 문제를 제출해본 다음, {{파일이름}}.log 에 채점 결과가 담김.

**Comment by minhoryang** [comment]
몇가지 문제가 있는데,
- [X] 1. [제대로 된 파이선을 못찾음. 환경변수 문제인데 강제로 시스템기본 3.4를 쓰게 만듬](https://github.com/juice-ryang/online-judge/commit/71b2752462e95fb3c06de90aadc16aaf87fe5594#diff-621b95de094594518e98fa16bd80aebaR153) (Celery.conf를 쓰자)
- [x] 2. [채점결과를 받아오는 자료구조 필요](https://github.com/juice-ryang/online-judge/commit/71b2752462e95fb3c06de90aadc16aaf87fe5594#diff-6951243ae32c6c63ce853a3d15f8d056R52)
- [x] 3. 라이브로 채점결과를 제공하는 부분 (어떤 방식을 쓰고, 어떤 정보를 제공할 수 있나)
- [X] 4. 실제 채점 데이터를 긁어오는 부분 (@juice500, #12)
- [ ] 5. 단순 실행 후 비교(.in/.out), 실패시 분석하도록(.json)
- [x] 6. 위와 같은 경우 웹UI를 어떻게 제공할 것인가?
- [ ] 7. 진행도%를 제공할 수 있나.
- [X] 8. 큰 task를 작은 subtask로 쪼갤 수 있나?
- [x] 9. 그 때 결과는 어떻게 취합해야하나?
- [x] 10. 이유가 짐작가는 버그가 하나 있는데 "Celery에서 결과를 제공받지 못함"

**Comment by minhoryang** [comment]
3. 라이브로 채점결과를 제공하는 부분
4. 실제 채점 데이터를 긁어오는 부분 (@juice500)

**Comment by minhoryang** [comment]
이유가 짐작가는 버그가 하나 있는데 "Celery에서 결과를 제공받지 못함"

**Comment by juice500ml** [comment]
Celery 환경 어떻게 만드나요 ㅠㅠ

**Comment by minhoryang** [comment]
@juice500ml 아... makefile을 보면 조금 나와있을거야 ㅠㅠ

``` bash
sudo make sudo-install
make install
```

지금 내 makefile에는 몇가지 제한사항이 있는데,
- onlinejudge계정을 만들고,
- 그 계정의 홈폴더 안에 online-judge 라고 우리 리파지토리를 클론한다음,
- pyenv를 3.5.1-onlinejudge 라고 만들어야해.

**Comment by minhoryang** [comment]
궁금하면 109접속해봐!

**Comment by minhoryang** [comment]
커밋아이디를 언급하지 않았는데, 1번 8번 해결됨

**Comment by minhoryang** [comment]
4번도 해결됨

**Comment by minhoryang** [comment]
812b8d030ca20617ae4d0bd258babcdfed56e88b
b9cdefcdaf3c1a55d088f0809b4c1ff2f25ea6fb
12a5e4219a5f5fdcfe1336f60d0cf5d34f935b06

**Comment by minhoryang** [comment]
5는 안됨. in/out을 먼저 할 수 없음.
