### ISSUE TITLE
400 /static/codemirror/lib/codemirror.js .css

### ISSUE THREAD

**Issue by minhoryang** [juice-ryang/online-judge#2]
/static/codemirror/lib/codemirror.js Failed to load resource: the server responded with a status of 404 (NOT FOUND)
/static/codemirror/lib/codemirror.css Failed to load resource: the server responded with a status of 404 (NOT FOUND)

**Comment by juice500ml** [comment]
fixed 20f6709b15a1ac02cdcbe16c790ebd1aad80bdea
