### ISSUE TITLE
광희가 디버그 할 수가 없어욧! 배포방식을 바꿉시다!

### ISSUE THREAD

**Issue by minhoryang** [juice-ryang/online-judge#22]
onlinejudge라는 계정을 만들기 싫대욧. (그건 저도 그래욧)

**Comment by minhoryang** [comment]
supervisord를 없앨까?

**Comment by minhoryang** [comment]
그럼 프로세스 관리를 어떻게 할까욧?

**Comment by minhoryang** [comment]
이 고민은 조금 나중에!

**Comment by minhoryang** [comment]
#21, #19 의 환경변수 문제는, 앞으로 여기서 처리합니다.

**Comment by minhoryang** [comment]
**Vagrant가 왜 그냥 싫은가 봤더니 RUBY에요!!!! 살려줘욧!!!!!ㅠㅠ**

**Comment by juice500ml** [comment]
아니이런ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ낭패갘ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by minhoryang** [comment]
이거 부터 먼저 할려고, Vagrant의 후계자 otto를 깔았는데,...
얘도  vagrant깔래서 발암중...ㅠㅠ

**Comment by minhoryang** [comment]
[실시간 발암, 이젠 vagrant를 통해 virtualbox를 설치한다.... ㅅㅂ](http://r.reluv.me/fQAz)

**Comment by juice500ml** [comment]
으핰

**Comment by juice500ml** [comment]
아옼ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ text-based horror story...

**Comment by minhoryang** [comment]
지금 진심 할까말까 고민중.

**Comment by minhoryang** [comment]
우선 한번은 해볼래

**Comment by minhoryang** [comment]
그동안 DB를 없앨 수 있겠다 젠장 DB없애고와야지

**Comment by minhoryang** [comment]
https://twitter.com/angryonhim/status/709779936102391808

**Comment by minhoryang** [comment]
사실 이제 되잖아요? 닫습니다!

광희는 Linux를 쓰므로 dockerize-mount 브랜치를 쓰고, 저는 dockerize 브랜치를 쓸겁니다.
