### ISSUE TITLE
관리자 페이지를 만들겠다구요구요구요?

### ISSUE THREAD

**Issue by minhoryang** [juice-ryang/online-judge#26]

**Comment by juice500ml** [comment]
관리자가 쓸만한 .sh나 .py를 만드는게 더 나을듯 해용!

**Comment by minhoryang** [comment]
음?! 그건 makefile에 조금 있긴한데. 쉘에 접속하는거 괜찮겠어요? 지금도 `make debug-corp`하면 서버에 접속되긴 하는데;;

**Comment by juice500ml** [comment]
아아 그것보다도 문제답.py랑 testinput.tar를 넣으면 폴더구조를 알아서 만들어주는 거같은거요..?

**Comment by juice500ml** [comment]
위키를 제대로 쓰는게 맞는 것 같습니다. 클로즈.
