### ISSUE TITLE
문제집 리프레시 기능좀요.

### ISSUE THREAD

**Issue by minhoryang** [juice-ryang/online-judge#27]
근데 생각해보니까 문제집 바꿀려면 쉘에서 심볼릭을 걸어주고 그래야하는데...
결국 수동이 낫나..

**Comment by juice500ml** [comment]
특정 링크를 가서 아이디/비번을 치는 생각을 했는데, 그게 관리자페이지라는 생각이 들더라구요.

**Comment by minhoryang** [comment]
관리자페이지로 넘기죳. #26
