### ISSUE TITLE
web 편집기?

### ISSUE THREAD

**Issue by juice500ml** [juice-ryang/online-judge#3]
pros. 파일 업로드 필요성 없어짐.
cons. 중간에 날아가도 어떻게 저장해줄 방법이 없음.

**Comment by minhoryang** [comment]
전 파일 업로드 방식이 더 마음에 들고 편하다고 생각합니다!
web에서 편집하게하면 생기는 문제는, 코드 전부가 http body안에 포함되는데, 이걸 우리가 저장해야하고, 전달과정에 코드가 적나라하게 전달되기때문에 서강대 방화벽에서 막힐 수 도 있다는 생각이 듭니다.

**Comment by juice500ml** [comment]
쓰지 않도록 결정하겠습니다.
