### ISSUE TITLE
table is not pretty

### ISSUE THREAD

**Issue by juice500ml** [juice-ryang/online-judge#34]
- Expected / Output / Difference 길이 맞추기
- diff가 엔터 다 짤라버림!

**Comment by minhoryang** [comment]
1. 이거 `/n`을 `<br>`로 바꾸는걸, JS단에서 하면 문제가 안생길 수도 있다는 생각이 들었어요!
   작업시작해볼게요.
2. 길이맞추는건 그 다음으로 하죠.

**Comment by minhoryang** [comment]
음?!?... 
![2016-03-23 6 27 04](https://cloud.githubusercontent.com/assets/1270855/13981014/e1396802-f124-11e5-8fad-cf231d5ab69a.png)

**Comment by minhoryang** [comment]
`<pre>`만세이!!!!!!!!

**Comment by minhoryang** [comment]
머지합니다
