### ISSUE TITLE
결과화면 나올 때, 항상 바닥으로 스크롤 해줄 수 있나요?

### ISSUE THREAD

**Issue by minhoryang** [juice-ryang/online-judge#36]
그러면 좋지 않을까요?

**Comment by juice500ml** [comment]
@taeguk 스크롤 어떻게 하는건가요? 수강신청 페이지 만들 때 자동으로 밑으로 내려가는거요!

**Comment by juice500ml** [comment]
d01eeca444a2f7ec834b4de00abfd9014bffca1a fixed.
