### ISSUE TITLE
제출한 코드를 어떻게 저장? (채점 큐를 어떻게 만듦?)

### ISSUE THREAD

**Issue by juice500ml** [juice-ryang/online-judge#4]
1. DB를 채점 큐처럼 사용한다.
2. ...

**Comment by minhoryang** [comment]
첨부파일로 받아서, Celery의 Queue에 넣는다. (DB없이)

**Comment by minhoryang** [comment]
User-->첨부파일-->Celery-->http-->Socket.io-->User

어제까지 작업했던 결과물이 v1.0.0으로 업로드되었습니다!
[releases/tag/v1.0.0](../releases/tag/v1.0.0) 
Judge.juice500.ml와 Judge.vita500.ml로 제공됩니다

만 여러가지 문제가 있어서 이를 해결하는 v2.0.0이 나올 예정입니다.
