### ISSUE TITLE
sample.py 넣으면 세 번째 테스트케이스에서 영원히 Pending 상태에요ㅠㅠ

### ISSUE THREAD

**Issue by juice500ml** [juice-ryang/online-judge#42]
test 해본 커밋은 c28673a8823794fd13c0ca6ccb72066d5b4c1090 fc1d455c8d472c112388928b678491c31c8a462b 두 군데에서 모두 발견할 수 있습니당

**Comment by minhoryang** [comment]
가끔가다 발생해요. docker화 하는 문제에서 발생한게 아니라.
DB에 채점 결과를 업데이트 할 때,
1. 채점 시간을 업데이트 하고,
2. 채점 결과를 업데이트 하는데

둘 사이에서 업데이트를 받아버리면,
최신 채점 결과를 받아오지 않습니다 ;ㅅ;ㅠㅠ

**Comment by minhoryang** [comment]
시간기준으로 하는게 아니라, MD5나 Hash나 뭐 이런 것으로 최신을 확인해야할 것 같습니다!

**Comment by minhoryang** [comment]
flask-cache같은걸 찾아봐야할듯.

**Comment by minhoryang** [comment]
MySQL이 datetime에 milliseconds를 저장하지 않아서 생기는 문제였습니다.
SQLAlchemy.Dialect.MYSQL.DATETIME같은걸 넣으면 되는데.... 음... 굳이 넣어야하나 싶어서 안넣었습니다.

해결은 String으로 저장하도록..
