### ISSUE TITLE
trailing whitespace problem (각 문장의 끝에 Whitespace가 들어있어도 좀 Flexible하게 채점해주기로 했어요!)

### ISSUE THREAD

**Issue by juice500ml** [juice-ryang/online-judge#44]
만약 답이 "aewaefwafwe       (trailing whitespaces)            \nLAST" 이라면, "aewaefwafwe\nLAST"도 허용해주어야하지 않을까요?

**Comment by juice500ml** [comment]
엔터 기준으로 잘랐을 때, 엔터 직전에 오는, 즉 afjwep fe(whitespace)\n에서의 (whitespace)는 없어도 됩니다. 그러므로, string을 엔터 기준으로 split한 list에 대하여, 맨 마지막 element를 제외한 직전 모든 element들에 대해 rsplit()을 하면 됩니다. (맨 마지막 element는, 다음에 올게 뭐가 올지 모르기 때문에 삭제하면 안됩니다. 사실 대부분의 경우 input이 오기 위한 prompt일 것이기 때문에 없애면 안돼요.) (오른쪽의 모든 whitespace를 모두 잘라줌) 그러고 join을 하면 해결!

**Comment by minhoryang** [comment]
#41 more 키모찌
