### ISSUE TITLE
Trailing chars after answer, but judge ignores

### ISSUE THREAD

**Issue by juice500ml** [juice-ryang/online-judge#45]
정답이 "aaa\n"이고 입력이 "aaa\naaaaaaa"인 경우 맞다고 채점!

Found while solving #44

**Comment by minhoryang** [comment]
![2016-04-12 11 14 09](https://cloud.githubusercontent.com/assets/1270855/14463035/7ff66802-0104-11e6-83ee-f49f86c25c19.png)

**Comment by minhoryang** [comment]
예상) 마지막 PASS 다음에 LEFT가 남았으므로, FAIL을 띄워야한다.
현실) LEFT는 무시된다.

**Comment by minhoryang** [comment]
문제는. 맨 마지막인데도. 추가적으로 FAIL을 띄워야 하나?!
(이게 아마 안될것 왜냐면 테스트케이스의 사이즈가 N이라는 것을 테스트 전에 이미 알고있는 부분이 있을 것?)
(하지만 이렇게 하고 싶은게 내 마음)

쉬운(?) 해결 방안은, 자신이 마지막 테스트 케이스 일 경우, LEFT가 있으면 PASS를 띄우지 말기!
