### ISSUE TITLE
[BUG] 모달 안에 codemirror의 Default String이 보이지 않음.

### ISSUE THREAD

**Issue by juice500ml** [juice-ryang/online-judge#7]
클릭 해야 볼 수 있음.

**Comment by juice500ml** [comment]
https://github.com/juice-ryang/online-judge/compare/6baa04536bb023504af39f373b9a6e5a9c589c92...b717eaf9eb8c0ac4c062c65d7ffffa459be4dc4c

이렇게 고쳐도 안보임.

**Comment by minhoryang** [comment]
codemirror를 나중으로 빼는게 좋을 것 같아요!

**Comment by minhoryang** [comment]
#3 에서 처리합니다.
